# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-11-04 23:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gatos', '0002_gato_comida'),
    ]

    operations = [
        migrations.AddField(
            model_name='gato',
            name='sexo',
            field=models.CharField(choices=[(b'M', b'Masculino'), (b'F', b'Femenino')], default='Masculino', max_length=10),
            preserve_default=False,
        ),
    ]
