# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-11-06 23:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Planetas', '0002_auto_20161106_2250'),
    ]

    operations = [
        migrations.CreateModel(
            name='Habitantes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('species', models.CharField(max_length=15)),
                ('number', models.IntegerField(default=0, null=True)),
                ('smart', models.BooleanField(default=False)),
            ],
        ),
    ]
