# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-11-06 23:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Planetas', '0003_habitantes'),
    ]

    operations = [
        migrations.AddField(
            model_name='planeta',
            name='especie',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='planeta_especie', to='Planetas.Habitantes'),
            preserve_default=False,
        ),
    ]
